#=========#
# STAGE 1 #
#=========#
FROM docker.io/oven/bun:slim AS builder
WORKDIR /app

COPY package.json bun.lock ./
RUN bun i --frozen-lockfile

COPY . .
RUN bun run build

#=========#
# STAGE 2 #
#=========#
FROM docker.io/nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
