FROM python:3.14-slim

# Prevents Python from writing .pyc files to disk
ENV PYTHONDONTWRITEBYTECODE=1
# Ensures stdout/stderr logs are sent straight to terminal without buffering
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --root-user-action ignore --no-cache-dir --upgrade pip && \
    pip install --root-user-action ignore --no-cache-dir -r requirements.txt

COPY . .

# Don't run as root
RUN useradd -u 1001 erbck && chown -R erbck:erbck /app
USER erbck

EXPOSE 8000

CMD ["python", "run.py"]
