---
name: PR Test Persona
"on":
  pull_request:
    branches:
      - master
    paths:
      - "frontend/**"
      - "!frontend/README.md"
      - "!frontend/.gitignore"
      - "!frontend/bun.lock"
      - ".github/workflows/build-frontend-edge.yaml"
  workflow_dispatch: {}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: frontend
          file: ./frontend/Containerfile
          push: false
          tags: ghcr.io/flamboyantpenguin/eventroots/persona:pr-${{ github.event.number }}
          outputs: type=oci,dest=/tmp/persona-pr-image.tar
          platforms: linux/amd64,linux/arm64

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v7
        with:
          name: persona-pr-image
          path: /tmp/persona-pr-image.tar
          retention-days: 4
